export type TransportEntry = {
  person: string
  type: 'bus' | 'self'
  direction?: string
  detail?: string
}

export const transportEntries: TransportEntry[] = [
  { person: 'Алешина Анна Дмитриевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Берест Алексей Алексадрович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Богунов Михаил Сергеевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Быков Георгий Сергеевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Голотова Ирина Викторовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Дружкова Светлана', type: 'bus', direction: 'туда и обратно' },
  { person: 'Евлахова Дарья Олеговна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Ерофеев Денис Николаевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Завоеванов Денис Кобилович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Касьянов Даниил Вадимович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Кузнецов Максим Игоревич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Ласурия Владислав Вадимович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Лебедев Евгений Александрович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Ледянкина Надежда Николаевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Макаренко Елена Станиславовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Максимов Сергей Федорович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Манько Евгения Олеговна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Мельникова Евгения Валерьевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Михаил Шилов', type: 'bus', direction: 'туда и обратно' },
  { person: 'Мустафина Камилла Салаватовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Мухлаева Анна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Неплях Артем', type: 'bus', direction: 'только в МСК' },
  { person: 'Онуфриенко Андрей Владимирович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Осина Мария Владимировна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Осипов Роман Александрович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Оха Анна Дмитриевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Павловский Дмитрий Сергеевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Попова Юлия Валерьевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Пройдакова Виктория Владимировна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Прокопенко Артём', type: 'bus', direction: 'туда и обратно' },
  { person: 'Ралдугин Александр Михайлович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Сидорова Елизавета Денисовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Синицына Ксения Романовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Сметанников Александр Владимирович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Соколов Данил Дмитриевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Таджибаев Руслан Азизович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Талапин Максим Игоревич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Трясцин Михаил Викторович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Тыртов Александр Сергеевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Ушакова Олеся Николаевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Федусь Анастасия Сергеевна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Цветков Иван Алексеевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Чехломин Сергей Валентинович', type: 'bus', direction: 'туда и обратно' },
  { person: 'Шайнога Максим Васильевич', type: 'bus', direction: 'туда и обратно' },
  { person: 'Шамсутдинова Алия Илюсовна', type: 'bus', direction: 'туда и обратно' },
  { person: 'Шешкин Сергей', type: 'bus', direction: 'только из МСК' },
  { person: 'Шибанов Мирон', type: 'bus', direction: 'туда и обратно' },
  { person: 'Шольчев Владислав', type: 'bus', direction: 'туда и обратно' },
  { person: 'Юсупова Арина', type: 'bus', direction: 'туда и обратно' },
  { person: 'Белоусова Татьяна Валерьевна', type: 'self' },
  { person: 'Бижов Илья', type: 'self', detail: 'на машине' },
  { person: 'Бычкова Екатерина Валерьевна', type: 'self', detail: 'на машине' },
  { person: 'Голобородова Сабина Гейсовна', type: 'self', detail: 'на машине' },
  { person: 'Горлова Виктория', type: 'self', detail: 'на машине' },
  { person: 'Денишев Роман', type: 'self', detail: 'на машине' },
  { person: 'Драгоций Василиса Валерьевна', type: 'self', detail: 'на машине' },
  { person: 'Елисеева Ксения Николаевна', type: 'self', detail: 'на машине' },
  { person: 'Ефимова Дарья Антоновна', type: 'self', detail: 'на машине' },
  { person: 'Зайкина Кристина Сергеевна', type: 'self', detail: 'на машине' },
  { person: 'Ивлева Юлия Анатольевна', type: 'self', detail: 'на машине' },
  { person: 'Климов Станислав Андреевич', type: 'self', detail: 'на машине' },
  { person: 'Кузин Дмитрий Юрьевич', type: 'self', detail: 'на машине' },
  { person: 'Леонов Егор Вячеславич', type: 'self', detail: 'на машине' },
  { person: 'Ломакин Денис Владимирович', type: 'self', detail: 'на машине' },
  { person: 'Макушин Вячеслав Романович', type: 'self', detail: 'на такси' },
  { person: 'Моргунова Ольга Дмитриевна', type: 'self', detail: 'на машине' },
  { person: 'Никитин Артём Валерьевич', type: 'self', detail: 'на машине' },
  { person: 'Паламарчук Дмитрий Иванович', type: 'self', detail: 'на машине' },
  { person: 'Помящий Никита', type: 'self', detail: 'на машине' },
  { person: 'Попов Виталий', type: 'self', detail: 'на машине' },
  { person: 'Предеин Стефан Сергеевич', type: 'self', detail: 'на машине' },
  { person: 'Провизион Катя', type: 'self', detail: 'на машине' },
  { person: 'Провизион Миша', type: 'self', detail: 'на машине' },
  { person: 'Салтыков Олег Витальевич', type: 'self' },
  { person: 'Седин Артем Витальевич', type: 'self', detail: 'на машине' },
  { person: 'Смирнов Павел Георгиевич', type: 'self', detail: 'на машине' },
  { person: 'Стельмах Александр', type: 'self', detail: 'на машине' },
  { person: 'Халамоник Елена Александровна', type: 'self', detail: 'на машине' },
  { person: 'Юрманова Галя', type: 'self', detail: 'на машине' },
]
